name: stevertus
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: Schueler209 <schueler109@jbs-pinneberg.de>

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  angular: ^6.0.0
  angular_router: ^2.0.0
  angular_forms: ^3.0.0
  http:
  fluix_web:
    path: C:\dev\Dart\stevertus\fluix-web
  ng_translate:
    path: C:\dev\Dart\stevertus\ng_translate
  objd:
    path: C:\dev\Dart\ObjectiveD
  objd_crafting:
    path: C:\dev\Dart\objd_crafting
  objd_gui:
    path: C:\dev\Dart\objd_gui

dev_dependencies:
  intl_translation:
  sass_builder:
  angular_test: ^2.3.0
  build_runner: ^1.6.0
  build_test: ^0.10.8
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
  test: ^1.6.0
