name: stevertus
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  angular: ^7.0.2
  angular_router: ^3.0.1
  angular_forms: ^4.0.1
  http: ^0.13.4
  ngsecurity:
    git: https://github.com/angulardart-community/ngsecurity.git
  fluix_web:
    path: ./fluix-web
  ng_translate:
    path: ./ng_translate
  objd:
  objd_crafting:
  objd_gui:

dev_dependencies:
  sass_builder:
  build_runner: ^2.1.7
  build_web_compilers:
  lints:
